Add Middleware protocols
halcyonmobile/RestBird pull request #16
Opened 2019-01-15 23:34 UTC by magyarosibotond

2019-01-18 07:48 UTC, mmellau requested changes

2019-01-18 07:48 UTC, mmellau commented on Sources/RestBird/NetworkClient.swift
> +    private(set) var preMiddlewares: [PreMiddleware] = []
The middlewares are exposed on purpose?

2019-01-18 07:59 UTC, mvalti commented on Sources/RestBird/NetworkClient.swift
> +// MARK: - Se
Fix MARK description

2019-01-18 08:28 UTC, tamassslv commented on Sources/RestBird/Session/SessionManager.swift
> +    var delegate: SessionManagerDelegate? { get set }
shouldn;t this be weak?

2019-01-18 08:28 UTC, tamassslv commented on Sources/RestBird/Session/SessionManager.swift
> +    var delegate: SessionManagerDelegate? { get set }
Or you can;t do that on protocols?

2019-01-18 08:35 UTC, mmellau commented on Sources/RestBird/Session/SessionManager.swift
> +    var delegate: SessionManagerDelegate? { get set }
That's right, you can't do that in protocols.

2019-01-18 09:25 UTC, magyarosibotond commented on Sources/RestBird/NetworkClient.swift
> +    private(set) var preMiddlewares: [PreMiddleware] = []
Yes, in case you want to look over them.

2019-01-18 09:26 UTC, magyarosibotond commented on Sources/RestBird/Session/SessionManager.swift
> +    var delegate: SessionManagerDelegate? { get set }
Correct. While declaring delegates as weak inside the protocol does compile at this moment, it will raise an error in future version of Swift.

> 'weak' should not be applied to a property declaration in a protocol and will be disallowed in future versions.

2019-01-18 10:18 UTC, mmellau approved these changes

2019-01-18 12:41 UTC, anieduard approved these changes

2019-01-18 12:49 UTC, mvalti approved these changes

2019-02-05 12:20 UTC, magyarosibotond commented
Alamofire Adapter interface will stay untouched in order to not to loose features from the freamework.

2019-02-05 12:22 UTC, merged